version: '3'

services:
    db:
        container_name: db
        image: mariadb:10.1
        ports:
            - 33061:3306
        restart: always
        volumes:
            - ./docker/data/db:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: p;\P!`2#-^%BEyp6
            MYSQL_DATABASE: buffer
            MYSQL_USER: buffer
            MYSQL_PASSWORD: ^6tS.F/Mx.@?!$Rd
        networks:
            - app

    php:
        container_name: php
        build: docker/php/
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - /etc/timezone:/etc/timezone:cached
        networks:
            - app

    nginx:
        container_name: nginx
        image: nginx:1.16.0-alpine
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        networks:
            - app

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local