api_register:
    resource: App\Controller\RegistrationController
    type: annotation
    prefix: api

api_login_check:
    path: /api/login_check

platforms:
    type: rest
    resource: App\Controller\PlatformController
    prefix: api