#index:
#    path: /
#    controller: App\Controller\DefaultController::index

registration:
    resource: App\Controller\RegistrationController
    type: annotation

api_login_check:
    path: /api/login_check

swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

swagger:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }