api_register:
    resource: App\Controller\RegistrationController
    type: annotation
    prefix: api

api_login_check:
    path: /api/login_check

platforms:
    resource: App\Controller\PlatformController
    type: annotation
    prefix: api

big_groups:
    resource: App\Controller\BigGroupController
    type: annotation
    prefix: api

events:
    resource: App\Controller\EventController
    type: annotation
    prefix: api